# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'Free Trial(9933f47c-be68-438b-9790-737373894a43)'
    KeyVaultName: 'kvazdevops'
    SecretsFilter: '*'
    RunAsPreJob: false
-script: echo $(Password)
